service: serverless-tensorflow

package:
  exclude:
    - .gitignore
    - README.md
    - package.json
    - package-lock.json
    - node_modules/**
    - venv/**
    - build_vendored.sh
    - clean_venv.sh
    - data/**
    - train_model.py
    - __pycache__/**
    - model/**
    - upload_model.py
    - model.zip
    - run_model.py

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  timeout: 30
  environment:
    MODEL_ZIP_FILE_NAME_ENV_VAR : 'magpie-model.zip'
    MODEL_KERAS_FILE_NAME_ENV_VAR : 'keras_model.h5'
    MODEL_SCALER_FILE_NAME_ENV_VAR : 'scaler'
    MODEL_LABELS_FILE_NAME_ENV_VAR : 'labels.pkl'
    MODEL_W2V_FILE_NAME_ENV_VAR : 'w2v_model'
    S3_MODEL_BUCKET_NAME_ENV_VAR : 'magpie-model'

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::magpie-model"
        - "arn:aws:s3:::magpie-model/*"

functions:
  predict:
    handler: handler.predict
    events:
      - http:
          path: /
          method: post
          cors: true