service: serverless-tensorflow

package:
  exclude:
    - .gitignore
    - README.md
    - package.json
    - package-lock.json
    - node_modules/**
    - venv/*
    - build_vendored.sh
    - clean_venv.sh

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-west-1
  timeout: 30

functions:
  predict:
    handler: handler.main