service: serverless-tensorflow

package:
  exclude:
    - .gitignore
    - README.md
    - package.json
    - package-lock.json
    - node_modules/**
    - venv/*
    - build_vendored.sh
    - clean_venv.sh
    - data/**
    - train_model.py
    - __pycache__/**
    - model/**
    - upload_model.py
    - model.zip

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  timeout: 30
  environment:
    TF_AWS_MODEL_ZIP_FILE_NAME: model.zip
    TF_AWS_S3_MODEL_BUCKET_NAME: magpie-model
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::magpie-model"
        - "arn:aws:s3:::magpie-model/*"

functions:
  predict:
    handler: handler.predict
    events:
      - http:
          path: /
          method: post
          cors: true